CC = gcc
CFLAGS = -Wall -Werror

SRCS = main.c supervisor/camera_supervisor.c supervisor/environment_supervisor.c IPC/ipc.c process/handling.c
OBJS = $(SRCS:.c=.o)
DEPS = $(SRCS:.c=.h) util.h

TARGET = operating_system_IPC_and_synchronisation

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET)

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean