//
// Created by Titouan LEBOCQ on 03/05/2023.
//

#ifndef OPERATING_SYSTEM_IPC_AND_SYNCHRONISATION_CAMERA_SUPERVISOR_H
#define OPERATING_SYSTEM_IPC_AND_SYNCHRONISATION_CAMERA_SUPERVISOR_H

#endif //OPERATING_SYSTEM_IPC_AND_SYNCHRONISATION_CAMERA_SUPERVISOR_H
