//
// Created by Titouan LEBOCQ on 03/05/2023.
//

#ifndef OPERATING_SYSTEM_IPC_AND_SYNCHRONISATION_ENVIRONMENT_SUPERVISOR_H
#define OPERATING_SYSTEM_IPC_AND_SYNCHRONISATION_ENVIRONMENT_SUPERVISOR_H

#define NO_WIND         0.0
#define SMALL_WIND      0.4
#define MEDIUM_WIND     1.5
#define STRONG_WIND     2.5

#endif //OPERATING_SYSTEM_IPC_AND_SYNCHRONISATION_ENVIRONMENT_SUPERVISOR_H
